name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Build Wheel
      run: |
        sudo apt install gcc-arm-none-eabi
        python -m pip install --upgrade pip
        pip wheel .
