name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install pyroxene and dependencies
      run: |
        sudo apt install gcc-arm-none-eabi
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test
      run: |
        python runtests.py -v test/*.py
